server:
  port: ${SERVER_PORT:8080}
  error:
    include-message: always
spring:
  data:
    mongodb:
      uri: ${DATABASE_URL:mongodb://localhost:27017}
    redis:
      password: ${REDIS_PASSWORD}
security:
  jwt:
    secret: MyLolSecretMotherFuckerSupremeJustLoooong
    expiration: 28800
  password-encoder:
    secret: hahaMylol
    iteration: 35
    keylength: 256
logging:
  level:
    root: info
    org.mongodb: warn
    reactor: warn

